name: 1-1 | Create | Remote state
on:
  workflow_dispatch
env:
  REGION: ${{ vars.REGIAO }}
  REMOTE_STATE_BUCKET: ${{ vars.REMOTE_STATE_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_CLI_ADMIN_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SECRET }}

jobs:
  main_job:
    name: "Create: Remote State"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: "Remote State: Run terraform init and apply."
      env:
        KEY_TF_STATE: "Remote State/terraform.tfstate"
        LOCAL_FOLDER: "1-Remote State"
      run: |
        chmod 755 ./generate_backend.sh && ./generate_backend.sh
        cd "./${{env.LOCAL_FOLDER}}"
        cp -f ./main.tf.local ./main.tf
        terraform init          
        terraform apply -auto-approve \
          -var "regiao=${{env.REGION}}" \
          -var "remote-state-bucket=${{env.REMOTE_STATE_BUCKET}}"
        cp -f ./main.tf.s3 ./main.tf
        terraform init -backend-config=backend.tfvars -input=false -force-copy
        terraform apply -auto-approve \
          -var "regiao=${{env.REGION}}" \
          -var "remote-state-bucket=${{env.REMOTE_STATE_BUCKET}}"