name: 3b-1 | Create | RDS Database
on: 
  workflow_dispatch
env:
  REGION: ${{ vars.REGIAO }}
  REMOTE_STATE_BUCKET: ${{ vars.REMOTE_STATE_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_CLI_ADMIN_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SECRET }}  

jobs:
  main_job:
    name: "Create: RDS Database"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: "RDS Database: Setup backend, run terraform init and apply."
      env:
        KEY_TF_STATE: "RDS Database/terraform.tfstate"
        LOCAL_FOLDER: "3b-RDS Database"
      run: |
        chmod 755 ./generate_backend.sh && ./generate_backend.sh
        cd "./${{env.LOCAL_FOLDER}}"
        terraform init -backend-config=./backend.tfvars
        terraform apply -auto-approve \
          -var "regiao=${{env.REGION}}" \
          -var "remote-state-bucket=${{env.REMOTE_STATE_BUCKET}}" \
          -var "rds-1-db-name=${{vars.RDS_1_DB_NAME}}" \
          -var "rds-1-db-username=${{vars.RDS_1_DB_USERNAME}}" \
          -var "rds-1-db-password=${{secrets.RDS_1_DB_PASSWORD}}"