name: 3h-1 | Create | S3 Static Files
on: 
  workflow_dispatch
env:
  REGION: ${{ vars.REGIAO }}
  REMOTE_STATE_BUCKET: ${{ vars.REMOTE_STATE_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_CLI_ADMIN_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SECRET }}  

jobs:
  main_job:
    name: "Create: S3 Static Files"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
          
    - name: "S3 Static Files: Setup backend, run terraform init and apply."
      env:
        KEY_TF_STATE: "S3 Static Files/terraform.tfstate"
        LOCAL_FOLDER: "3h-S3 Static Files"
      run: |
        chmod 755 ./generate_backend.sh && ./generate_backend.sh
        cd "./${{env.LOCAL_FOLDER}}"
        terraform init -backend-config=./backend.tfvars
        terraform apply -auto-approve \
          -var "regiao=${{env.REGION}}" \
          -var "remote-state-bucket=${{env.REMOTE_STATE_BUCKET}}" \
          -var "static-files-bucket-name=${{vars.STATIC_FILES_BUCKET_NAME}}"